// This file is auto-generated by @hey-api/openapi-ts

export type PostApiInternalArtifactsCheckDomainData = {
    body?: {
        botId: string;
        sessionKey?: string;
        chatId?: string;
        threadId?: string;
        channelType?: string;
        previewUrl: string;
    };
    path?: never;
    query?: never;
    url: '/api/internal/artifacts/check-domain';
};

export type PostApiInternalArtifactsCheckDomainErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
    /**
     * Domain already in use by another session
     */
    409: {
        message: string;
    };
};

export type PostApiInternalArtifactsCheckDomainError = PostApiInternalArtifactsCheckDomainErrors[keyof PostApiInternalArtifactsCheckDomainErrors];

export type PostApiInternalArtifactsCheckDomainResponses = {
    /**
     * Domain availability result
     */
    200: {
        available: boolean;
        sessionKey: string;
        existingArtifactId: string;
        existingSessionKey: string;
    };
};

export type PostApiInternalArtifactsCheckDomainResponse = PostApiInternalArtifactsCheckDomainResponses[keyof PostApiInternalArtifactsCheckDomainResponses];

export type PostApiInternalArtifactsData = {
    body?: {
        botId: string;
        title: string;
        sessionKey?: string;
        chatId?: string;
        threadId?: string;
        channelType?: string;
        channelId?: string;
        artifactType?: 'code' | 'content' | 'deployment';
        source?: 'coding' | 'content';
        contentType?: string;
        status?: 'building' | 'live' | 'failed' | 'stopped';
        previewUrl?: string;
        deployTarget?: string;
        linesOfCode?: number;
        fileCount?: number;
        durationMs?: number;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/api/internal/artifacts';
};

export type PostApiInternalArtifactsErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
    /**
     * Preview URL already in use by another session
     */
    409: {
        message: string;
    };
};

export type PostApiInternalArtifactsError = PostApiInternalArtifactsErrors[keyof PostApiInternalArtifactsErrors];

export type PostApiInternalArtifactsResponses = {
    /**
     * Artifact created
     */
    201: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        artifactType: string;
        source: string;
        contentType: string;
        status: string;
        previewUrl: string;
        deployTarget: string;
        linesOfCode: number;
        fileCount: number;
        durationMs: number;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiInternalArtifactsResponse = PostApiInternalArtifactsResponses[keyof PostApiInternalArtifactsResponses];

export type PatchApiInternalArtifactsByIdData = {
    body?: {
        title?: string;
        status?: 'building' | 'live' | 'failed' | 'stopped';
        previewUrl?: string;
        deployTarget?: string;
        linesOfCode?: number;
        fileCount?: number;
        durationMs?: number;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/internal/artifacts/{id}';
};

export type PatchApiInternalArtifactsByIdErrors = {
    /**
     * Artifact not found
     */
    404: {
        message: string;
    };
};

export type PatchApiInternalArtifactsByIdError = PatchApiInternalArtifactsByIdErrors[keyof PatchApiInternalArtifactsByIdErrors];

export type PatchApiInternalArtifactsByIdResponses = {
    /**
     * Artifact updated
     */
    200: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        artifactType: string;
        source: string;
        contentType: string;
        status: string;
        previewUrl: string;
        deployTarget: string;
        linesOfCode: number;
        fileCount: number;
        durationMs: number;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type PatchApiInternalArtifactsByIdResponse = PatchApiInternalArtifactsByIdResponses[keyof PatchApiInternalArtifactsByIdResponses];

export type PostApiInternalSessionsData = {
    body?: {
        botId: string;
        sessionKey: string;
        title: string;
        channelType?: string;
        channelId?: string;
        status?: 'active' | 'ended';
        messageCount?: number;
        lastMessageAt?: string;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/api/internal/sessions';
};

export type PostApiInternalSessionsErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
};

export type PostApiInternalSessionsError = PostApiInternalSessionsErrors[keyof PostApiInternalSessionsErrors];

export type PostApiInternalSessionsResponses = {
    /**
     * Session created or updated
     */
    201: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        status: string;
        messageCount: number;
        lastMessageAt: string;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiInternalSessionsResponse = PostApiInternalSessionsResponses[keyof PostApiInternalSessionsResponses];

export type PatchApiInternalSessionsByIdData = {
    body?: {
        title?: string;
        status?: 'active' | 'ended';
        messageCount?: number;
        lastMessageAt?: string;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/internal/sessions/{id}';
};

export type PatchApiInternalSessionsByIdErrors = {
    /**
     * Session not found
     */
    404: {
        message: string;
    };
};

export type PatchApiInternalSessionsByIdError = PatchApiInternalSessionsByIdErrors[keyof PatchApiInternalSessionsByIdErrors];

export type PatchApiInternalSessionsByIdResponses = {
    /**
     * Session updated
     */
    200: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        status: string;
        messageCount: number;
        lastMessageAt: string;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type PatchApiInternalSessionsByIdResponse = PatchApiInternalSessionsByIdResponses[keyof PatchApiInternalSessionsByIdResponses];

export type GetApiInternalSecretsBySkillNameData = {
    body?: never;
    path: {
        skillName: string;
    };
    query: {
        poolId: string;
    };
    url: '/api/internal/secrets/{skillName}';
};

export type GetApiInternalSecretsBySkillNameErrors = {
    /**
     * Unauthorized
     */
    401: {
        message: string;
    };
};

export type GetApiInternalSecretsBySkillNameError = GetApiInternalSecretsBySkillNameErrors[keyof GetApiInternalSecretsBySkillNameErrors];

export type GetApiInternalSecretsBySkillNameResponses = {
    /**
     * Scoped secrets for skill
     */
    200: {
        [key: string]: string;
    };
};

export type GetApiInternalSecretsBySkillNameResponse = GetApiInternalSecretsBySkillNameResponses[keyof GetApiInternalSecretsBySkillNameResponses];

export type GetApiInternalSkillsLatestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/internal/skills/latest';
};

export type GetApiInternalSkillsLatestErrors = {
    /**
     * Unauthorized
     */
    401: {
        message: string;
    };
};

export type GetApiInternalSkillsLatestError = GetApiInternalSkillsLatestErrors[keyof GetApiInternalSkillsLatestErrors];

export type GetApiInternalSkillsLatestResponses = {
    /**
     * Latest skills snapshot
     */
    200: {
        version: number;
        skillsHash: string;
        skills: {
            [key: string]: {
                [key: string]: string;
            };
        };
        createdAt: string;
    };
};

export type GetApiInternalSkillsLatestResponse = GetApiInternalSkillsLatestResponses[keyof GetApiInternalSkillsLatestResponses];

export type PutApiInternalSkillsByNameData = {
    body?: {
        content: string;
        files?: {
            [key: string]: string;
        };
        status?: 'active' | 'inactive';
    };
    path: {
        name: string;
    };
    query?: never;
    url: '/api/internal/skills/{name}';
};

export type PutApiInternalSkillsByNameErrors = {
    /**
     * Invalid name or body
     */
    400: {
        message: string;
    };
    /**
     * Unauthorized
     */
    401: {
        message: string;
    };
};

export type PutApiInternalSkillsByNameError = PutApiInternalSkillsByNameErrors[keyof PutApiInternalSkillsByNameErrors];

export type PutApiInternalSkillsByNameResponses = {
    /**
     * Skill upserted
     */
    200: {
        ok: boolean;
        name: string;
        version: number;
    };
};

export type PutApiInternalSkillsByNameResponse = PutApiInternalSkillsByNameResponses[keyof PutApiInternalSkillsByNameResponses];

export type GetApiInternalWorkspaceTemplatesLatestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/internal/workspace-templates/latest';
};

export type GetApiInternalWorkspaceTemplatesLatestErrors = {
    /**
     * Unauthorized
     */
    401: {
        message: string;
    };
};

export type GetApiInternalWorkspaceTemplatesLatestError = GetApiInternalWorkspaceTemplatesLatestErrors[keyof GetApiInternalWorkspaceTemplatesLatestErrors];

export type GetApiInternalWorkspaceTemplatesLatestResponses = {
    /**
     * Latest workspace templates snapshot
     */
    200: {
        version: number;
        templatesHash: string;
        templates: {
            [key: string]: {
                content: string;
                writeMode: 'seed' | 'inject';
            };
        };
        createdAt: string;
    };
};

export type GetApiInternalWorkspaceTemplatesLatestResponse = GetApiInternalWorkspaceTemplatesLatestResponses[keyof GetApiInternalWorkspaceTemplatesLatestResponses];

export type PutApiInternalWorkspaceTemplatesByNameData = {
    body?: {
        content: string;
        writeMode?: 'seed' | 'inject';
        status?: 'active' | 'inactive';
    };
    path: {
        name: string;
    };
    query?: never;
    url: '/api/internal/workspace-templates/{name}';
};

export type PutApiInternalWorkspaceTemplatesByNameErrors = {
    /**
     * Invalid name or body
     */
    400: {
        message: string;
    };
    /**
     * Unauthorized
     */
    401: {
        message: string;
    };
};

export type PutApiInternalWorkspaceTemplatesByNameError = PutApiInternalWorkspaceTemplatesByNameErrors[keyof PutApiInternalWorkspaceTemplatesByNameErrors];

export type PutApiInternalWorkspaceTemplatesByNameResponses = {
    /**
     * Template upserted
     */
    200: {
        ok: boolean;
        name: string;
        version: number;
    };
};

export type PutApiInternalWorkspaceTemplatesByNameResponse = PutApiInternalWorkspaceTemplatesByNameResponses[keyof PutApiInternalWorkspaceTemplatesByNameResponses];

export type PostApiInternalFeedbackData = {
    body?: {
        content: string;
        channel?: string;
        sender?: string;
        agentId?: string;
        conversationContext?: string;
        imageUrls?: Array<string>;
        imageData?: Array<{
            data: string;
            mimeType: string;
        }>;
        fileData?: Array<{
            data: string;
            fileName: string;
        }>;
    };
    path?: never;
    query?: never;
    url: '/api/internal/feedback';
};

export type PostApiInternalFeedbackErrors = {
    /**
     * Invalid body
     */
    400: {
        message: string;
    };
    /**
     * Unauthorized
     */
    401: {
        message: string;
    };
};

export type PostApiInternalFeedbackError = PostApiInternalFeedbackErrors[keyof PostApiInternalFeedbackErrors];

export type PostApiInternalFeedbackResponses = {
    /**
     * Feedback received
     */
    200: {
        ok: boolean;
    };
};

export type PostApiInternalFeedbackResponse = PostApiInternalFeedbackResponses[keyof PostApiInternalFeedbackResponses];

export type GetApiV1MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me';
};

export type GetApiV1MeResponses = {
    /**
     * Current user profile
     */
    200: {
        id: string;
        email: string;
        name: string;
        image?: string;
        plan: string;
        inviteAccepted: boolean;
        onboardingCompleted: boolean;
    };
};

export type GetApiV1MeResponse = GetApiV1MeResponses[keyof GetApiV1MeResponses];

export type PostApiV1OnboardingCompleteData = {
    body?: {
        role: string;
        company?: string;
        useCases: Array<string>;
        referralSource: string;
        referralDetail?: string;
        channelVotes?: Array<string>;
        selectedAvatar: string;
        avatarVotes?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/api/v1/onboarding/complete';
};

export type PostApiV1OnboardingCompleteResponses = {
    /**
     * Onboarding completed
     */
    200: {
        ok: boolean;
    };
};

export type PostApiV1OnboardingCompleteResponse = PostApiV1OnboardingCompleteResponses[keyof PostApiV1OnboardingCompleteResponses];

export type GetApiV1BotsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/bots';
};

export type GetApiV1BotsResponses = {
    /**
     * Bot list
     */
    200: {
        bots: Array<{
            id: string;
            name: string;
            slug: string;
            poolId: string;
            status: 'active' | 'paused' | 'deleted';
            modelId: string;
            systemPrompt: string;
            createdAt: string;
            updatedAt: string;
        }>;
    };
};

export type GetApiV1BotsResponse = GetApiV1BotsResponses[keyof GetApiV1BotsResponses];

export type PostApiV1BotsData = {
    body?: {
        name: string;
        slug: string;
        systemPrompt?: string;
        modelId?: string;
        poolId?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/bots';
};

export type PostApiV1BotsErrors = {
    /**
     * Invalid pool state
     */
    400: {
        message: string;
    };
    /**
     * Pool not found
     */
    404: {
        message: string;
    };
    /**
     * Slug already exists
     */
    409: {
        message: string;
    };
};

export type PostApiV1BotsError = PostApiV1BotsErrors[keyof PostApiV1BotsErrors];

export type PostApiV1BotsResponses = {
    /**
     * Bot created
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiV1BotsResponse = PostApiV1BotsResponses[keyof PostApiV1BotsResponses];

export type DeleteApiV1BotsByBotIdData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/v1/bots/{botId}';
};

export type DeleteApiV1BotsByBotIdErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type DeleteApiV1BotsByBotIdError = DeleteApiV1BotsByBotIdErrors[keyof DeleteApiV1BotsByBotIdErrors];

export type DeleteApiV1BotsByBotIdResponses = {
    /**
     * Bot deleted
     */
    200: {
        success: boolean;
    };
};

export type DeleteApiV1BotsByBotIdResponse = DeleteApiV1BotsByBotIdResponses[keyof DeleteApiV1BotsByBotIdResponses];

export type GetApiV1BotsByBotIdData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/v1/bots/{botId}';
};

export type GetApiV1BotsByBotIdErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type GetApiV1BotsByBotIdError = GetApiV1BotsByBotIdErrors[keyof GetApiV1BotsByBotIdErrors];

export type GetApiV1BotsByBotIdResponses = {
    /**
     * Bot details
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetApiV1BotsByBotIdResponse = GetApiV1BotsByBotIdResponses[keyof GetApiV1BotsByBotIdResponses];

export type PatchApiV1BotsByBotIdData = {
    body?: {
        name?: string;
        systemPrompt?: string;
        modelId?: string;
    };
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/v1/bots/{botId}';
};

export type PatchApiV1BotsByBotIdErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type PatchApiV1BotsByBotIdError = PatchApiV1BotsByBotIdErrors[keyof PatchApiV1BotsByBotIdErrors];

export type PatchApiV1BotsByBotIdResponses = {
    /**
     * Bot updated
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PatchApiV1BotsByBotIdResponse = PatchApiV1BotsByBotIdResponses[keyof PatchApiV1BotsByBotIdResponses];

export type PostApiV1BotsByBotIdPauseData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/v1/bots/{botId}/pause';
};

export type PostApiV1BotsByBotIdPauseErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type PostApiV1BotsByBotIdPauseError = PostApiV1BotsByBotIdPauseErrors[keyof PostApiV1BotsByBotIdPauseErrors];

export type PostApiV1BotsByBotIdPauseResponses = {
    /**
     * Bot paused
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiV1BotsByBotIdPauseResponse = PostApiV1BotsByBotIdPauseResponses[keyof PostApiV1BotsByBotIdPauseResponses];

export type PostApiV1BotsByBotIdResumeData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/v1/bots/{botId}/resume';
};

export type PostApiV1BotsByBotIdResumeErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type PostApiV1BotsByBotIdResumeError = PostApiV1BotsByBotIdResumeErrors[keyof PostApiV1BotsByBotIdResumeErrors];

export type PostApiV1BotsByBotIdResumeResponses = {
    /**
     * Bot resumed
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiV1BotsByBotIdResumeResponse = PostApiV1BotsByBotIdResumeResponses[keyof PostApiV1BotsByBotIdResumeResponses];

export type GetApiV1BotQuotaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/bot-quota';
};

export type GetApiV1BotQuotaResponses = {
    /**
     * Bot creation quota status
     */
    200: {
        available: boolean;
        resetsAt: string;
    };
};

export type GetApiV1BotQuotaResponse = GetApiV1BotQuotaResponses[keyof GetApiV1BotQuotaResponses];

export type GetApiV1ChannelsSlackRedirectUriData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/channels/slack/redirect-uri';
};

export type GetApiV1ChannelsSlackRedirectUriResponses = {
    /**
     * The OAuth redirect URI configured on this server
     */
    200: {
        redirectUri: string;
    };
};

export type GetApiV1ChannelsSlackRedirectUriResponse = GetApiV1ChannelsSlackRedirectUriResponses[keyof GetApiV1ChannelsSlackRedirectUriResponses];

export type GetApiV1ChannelsSlackOauthUrlData = {
    body?: never;
    path?: never;
    query?: {
        returnTo?: string;
    };
    url: '/api/v1/channels/slack/oauth-url';
};

export type GetApiV1ChannelsSlackOauthUrlErrors = {
    /**
     * Slack OAuth not configured
     */
    500: {
        message: string;
    };
};

export type GetApiV1ChannelsSlackOauthUrlError = GetApiV1ChannelsSlackOauthUrlErrors[keyof GetApiV1ChannelsSlackOauthUrlErrors];

export type GetApiV1ChannelsSlackOauthUrlResponses = {
    /**
     * Slack OAuth authorization URL
     */
    200: {
        url: string;
        redirectUri: string;
    };
};

export type GetApiV1ChannelsSlackOauthUrlResponse = GetApiV1ChannelsSlackOauthUrlResponses[keyof GetApiV1ChannelsSlackOauthUrlResponses];

export type PostApiV1ChannelsSlackConnectData = {
    body?: {
        botToken: string;
        signingSecret: string;
        teamId?: string;
        teamName?: string;
        appId?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/channels/slack/connect';
};

export type PostApiV1ChannelsSlackConnectErrors = {
    /**
     * Slack already connected
     */
    409: {
        message: string;
    };
};

export type PostApiV1ChannelsSlackConnectError = PostApiV1ChannelsSlackConnectErrors[keyof PostApiV1ChannelsSlackConnectErrors];

export type PostApiV1ChannelsSlackConnectResponses = {
    /**
     * Slack channel connected
     */
    200: {
        id: string;
        botId: string;
        channelType: 'slack' | 'discord' | 'feishu';
        accountId: string;
        status: 'pending' | 'connected' | 'disconnected' | 'error';
        teamName: string;
        appId?: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiV1ChannelsSlackConnectResponse = PostApiV1ChannelsSlackConnectResponses[keyof PostApiV1ChannelsSlackConnectResponses];

export type PostApiV1ChannelsDiscordConnectData = {
    body?: {
        botToken: string;
        appId: string;
        guildId?: string;
        guildName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/channels/discord/connect';
};

export type PostApiV1ChannelsDiscordConnectErrors = {
    /**
     * Discord already connected
     */
    409: {
        message: string;
    };
};

export type PostApiV1ChannelsDiscordConnectError = PostApiV1ChannelsDiscordConnectErrors[keyof PostApiV1ChannelsDiscordConnectErrors];

export type PostApiV1ChannelsDiscordConnectResponses = {
    /**
     * Discord channel connected
     */
    200: {
        id: string;
        botId: string;
        channelType: 'slack' | 'discord' | 'feishu';
        accountId: string;
        status: 'pending' | 'connected' | 'disconnected' | 'error';
        teamName: string;
        appId?: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiV1ChannelsDiscordConnectResponse = PostApiV1ChannelsDiscordConnectResponses[keyof PostApiV1ChannelsDiscordConnectResponses];

export type GetApiV1ChannelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/channels';
};

export type GetApiV1ChannelsResponses = {
    /**
     * Channel list
     */
    200: {
        channels: Array<{
            id: string;
            botId: string;
            channelType: 'slack' | 'discord' | 'feishu';
            accountId: string;
            status: 'pending' | 'connected' | 'disconnected' | 'error';
            teamName: string;
            appId?: string;
            createdAt: string;
            updatedAt: string;
        }>;
    };
};

export type GetApiV1ChannelsResponse = GetApiV1ChannelsResponses[keyof GetApiV1ChannelsResponses];

export type DeleteApiV1ChannelsByChannelIdData = {
    body?: never;
    path: {
        channelId: string;
    };
    query?: never;
    url: '/api/v1/channels/{channelId}';
};

export type DeleteApiV1ChannelsByChannelIdErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type DeleteApiV1ChannelsByChannelIdError = DeleteApiV1ChannelsByChannelIdErrors[keyof DeleteApiV1ChannelsByChannelIdErrors];

export type DeleteApiV1ChannelsByChannelIdResponses = {
    /**
     * Channel disconnected
     */
    200: {
        success: boolean;
    };
};

export type DeleteApiV1ChannelsByChannelIdResponse = DeleteApiV1ChannelsByChannelIdResponses[keyof DeleteApiV1ChannelsByChannelIdResponses];

export type GetApiV1ChannelsByChannelIdStatusData = {
    body?: never;
    path: {
        channelId: string;
    };
    query?: never;
    url: '/api/v1/channels/{channelId}/status';
};

export type GetApiV1ChannelsByChannelIdStatusErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetApiV1ChannelsByChannelIdStatusError = GetApiV1ChannelsByChannelIdStatusErrors[keyof GetApiV1ChannelsByChannelIdStatusErrors];

export type GetApiV1ChannelsByChannelIdStatusResponses = {
    /**
     * Channel status
     */
    200: {
        id: string;
        botId: string;
        channelType: 'slack' | 'discord' | 'feishu';
        accountId: string;
        status: 'pending' | 'connected' | 'disconnected' | 'error';
        teamName: string;
        appId?: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetApiV1ChannelsByChannelIdStatusResponse = GetApiV1ChannelsByChannelIdStatusResponses[keyof GetApiV1ChannelsByChannelIdStatusResponses];

export type PostApiV1InviteValidateData = {
    body?: {
        code: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/invite/validate';
};

export type PostApiV1InviteValidateResponses = {
    /**
     * Validation result
     */
    200: {
        valid: boolean;
        message?: string;
    };
};

export type PostApiV1InviteValidateResponse = PostApiV1InviteValidateResponses[keyof PostApiV1InviteValidateResponses];

export type GetApiV1ModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/models';
};

export type GetApiV1ModelsResponses = {
    /**
     * Available models
     */
    200: {
        models: Array<{
            id: string;
            name: string;
            provider: string;
            isDefault?: boolean;
            description?: string;
        }>;
    };
};

export type GetApiV1ModelsResponse = GetApiV1ModelsResponses[keyof GetApiV1ModelsResponses];

export type GetApiInternalPoolsByPoolIdConfigData = {
    body?: never;
    path: {
        poolId: string;
    };
    query?: never;
    url: '/api/internal/pools/{poolId}/config';
};

export type GetApiInternalPoolsByPoolIdConfigErrors = {
    /**
     * Pool not found
     */
    404: {
        message: string;
    };
};

export type GetApiInternalPoolsByPoolIdConfigError = GetApiInternalPoolsByPoolIdConfigErrors[keyof GetApiInternalPoolsByPoolIdConfigErrors];

export type GetApiInternalPoolsByPoolIdConfigResponses = {
    /**
     * Generated OpenClaw config
     */
    200: {
        gateway: {
            port?: number;
            mode?: 'local';
            bind?: 'loopback' | 'lan' | 'auto';
            auth: {
                mode: 'none' | 'token';
                token?: string;
            };
            reload?: {
                mode: 'off' | 'hot' | 'hybrid';
            };
            controlUi?: {
                allowedOrigins?: Array<string>;
                dangerouslyAllowHostHeaderOriginFallback?: boolean;
            };
        };
        models?: {
            mode?: 'merge' | 'replace';
            providers: {
                [key: string]: {
                    baseUrl: string;
                    apiKey: string;
                    api: string;
                    models: Array<{
                        id: string;
                        name?: string;
                        reasoning?: boolean;
                        input?: Array<string>;
                        cost?: {
                            input: number;
                            output: number;
                            cacheRead?: number;
                            cacheWrite?: number;
                        };
                        contextWindow?: number;
                        maxTokens?: number;
                        compat?: {
                            supportsStore?: boolean;
                        };
                    }>;
                };
            };
        };
        tools?: {
            exec?: {
                security?: 'deny' | 'allowlist' | 'full';
                ask?: 'off' | 'on-miss' | 'always';
                host?: 'sandbox' | 'gateway' | 'node';
            };
            web?: {
                search?: {
                    enabled?: boolean;
                };
                fetch?: {
                    enabled?: boolean;
                };
            };
        };
        skills?: {
            load?: {
                watch?: boolean;
                watchDebounceMs?: number;
                extraDirs?: Array<string>;
            };
        };
        agents: {
            defaults?: {
                model?: string | {
                    primary: string;
                };
                compaction?: {
                    mode?: 'default' | 'safeguard';
                    reserveTokens?: number;
                    keepRecentTokens?: number;
                    reserveTokensFloor?: number;
                    maxHistoryShare?: number;
                    memoryFlush?: {
                        enabled?: boolean;
                        softThresholdTokens?: number;
                        prompt?: string;
                    };
                };
                memorySearch?: {
                    enabled?: boolean;
                    sources?: Array<'memory' | 'sessions'>;
                    provider?: 'openai' | 'gemini' | 'local' | 'voyage' | 'mistral';
                    model?: string;
                    remote?: {
                        baseUrl?: string;
                        apiKey?: string;
                    };
                    sync?: {
                        intervalMinutes?: number;
                    };
                };
            };
            list: Array<{
                id: string;
                name?: string;
                default?: boolean;
                workspace?: string;
                model?: string | {
                    primary: string;
                    fallbacks?: Array<string>;
                };
            }>;
        };
        channels: {
            slack?: {
                mode?: 'socket' | 'http';
                signingSecret?: string;
                enabled?: boolean;
                groupPolicy?: 'open' | 'allowlist' | 'disabled';
                requireMention?: boolean;
                dmPolicy?: 'pairing' | 'allowlist' | 'open';
                allowFrom?: Array<string>;
                ackReaction?: string;
                accounts: {
                    [key: string]: {
                        enabled?: boolean;
                        botToken: string;
                        signingSecret?: string;
                        appToken?: string;
                        mode?: 'socket' | 'http';
                        webhookPath?: string;
                        dmPolicy?: 'pairing' | 'allowlist' | 'open';
                        groupPolicy?: 'open' | 'allowlist' | 'disabled';
                        streaming?: 'off' | 'partial' | 'block' | 'progress';
                    };
                };
            };
            discord?: {
                enabled?: boolean;
                groupPolicy?: 'open' | 'allowlist' | 'disabled';
                dmPolicy?: 'pairing' | 'allowlist' | 'open';
                allowFrom?: Array<string>;
                accounts: {
                    [key: string]: {
                        enabled?: boolean;
                        token: string;
                        groupPolicy?: 'open' | 'allowlist' | 'disabled';
                    };
                };
            };
            feishu?: {
                enabled?: boolean;
                connectionMode?: 'websocket' | 'webhook';
                dmPolicy?: 'pairing' | 'allowlist' | 'open';
                groupPolicy?: 'open' | 'allowlist' | 'disabled';
                requireMention?: boolean;
                allowFrom?: Array<string>;
                accounts: {
                    [key: string]: {
                        enabled?: boolean;
                        appId: string;
                        appSecret: string;
                    };
                };
            };
        };
        bindings: Array<{
            agentId: string;
            match: {
                channel: string;
                accountId?: string;
            };
        }>;
        commands?: {
            native?: 'auto' | 'off';
            nativeSkills?: 'auto' | 'off';
            restart?: boolean;
            ownerDisplay?: 'raw' | 'friendly';
        };
        cron?: {
            enabled?: boolean;
        };
        messages?: {
            ackReaction?: string;
            ackReactionScope?: 'off' | 'none' | 'all' | 'direct' | 'group-all' | 'group-mentions';
            removeAckAfterReply?: boolean;
        };
        diagnostics?: {
            enabled?: boolean;
            otel?: {
                enabled?: boolean;
                endpoint?: string;
                serviceName?: string;
                traces?: boolean;
                metrics?: boolean;
                logs?: boolean;
                flushIntervalMs?: number;
            };
        };
    };
};

export type GetApiInternalPoolsByPoolIdConfigResponse = GetApiInternalPoolsByPoolIdConfigResponses[keyof GetApiInternalPoolsByPoolIdConfigResponses];

export type PostApiInternalPoolsRegisterData = {
    body?: {
        poolId: string;
        podIp?: string;
        status?: 'pending' | 'active' | 'degraded' | 'unhealthy' | 'draining' | 'terminated';
    };
    path?: never;
    query?: never;
    url: '/api/internal/pools/register';
};

export type PostApiInternalPoolsRegisterResponses = {
    /**
     * Pool node registered
     */
    200: {
        ok: boolean;
        poolId: string;
    };
};

export type PostApiInternalPoolsRegisterResponse = PostApiInternalPoolsRegisterResponses[keyof PostApiInternalPoolsRegisterResponses];

export type PostApiInternalPoolsHeartbeatData = {
    body?: {
        poolId: string;
        podIp?: string;
        status?: 'pending' | 'active' | 'degraded' | 'unhealthy' | 'draining' | 'terminated';
        lastSeenVersion?: number;
        timestamp?: string;
    };
    path?: never;
    query?: never;
    url: '/api/internal/pools/heartbeat';
};

export type PostApiInternalPoolsHeartbeatResponses = {
    /**
     * Pool node heartbeat accepted
     */
    200: {
        ok: boolean;
        poolId: string;
        status: 'pending' | 'active' | 'degraded' | 'unhealthy' | 'draining' | 'terminated';
    };
};

export type PostApiInternalPoolsHeartbeatResponse = PostApiInternalPoolsHeartbeatResponses[keyof PostApiInternalPoolsHeartbeatResponses];

export type PutApiInternalPoolsByPoolIdSecretsData = {
    body?: {
        secrets: {
            [key: string]: string | {
                value: string;
                scope?: string;
            };
        };
    };
    path: {
        poolId: string;
    };
    query?: never;
    url: '/api/internal/pools/{poolId}/secrets';
};

export type PutApiInternalPoolsByPoolIdSecretsErrors = {
    /**
     * Pool not found
     */
    404: {
        message: string;
    };
};

export type PutApiInternalPoolsByPoolIdSecretsError = PutApiInternalPoolsByPoolIdSecretsErrors[keyof PutApiInternalPoolsByPoolIdSecretsErrors];

export type PutApiInternalPoolsByPoolIdSecretsResponses = {
    /**
     * Secrets stored
     */
    200: {
        ok: boolean;
        count: number;
    };
};

export type PutApiInternalPoolsByPoolIdSecretsResponse = PutApiInternalPoolsByPoolIdSecretsResponses[keyof PutApiInternalPoolsByPoolIdSecretsResponses];

export type GetApiInternalPoolsByPoolIdConfigLatestData = {
    body?: never;
    path: {
        poolId: string;
    };
    query?: never;
    url: '/api/internal/pools/{poolId}/config/latest';
};

export type GetApiInternalPoolsByPoolIdConfigLatestErrors = {
    /**
     * Pool not found
     */
    404: {
        message: string;
    };
};

export type GetApiInternalPoolsByPoolIdConfigLatestError = GetApiInternalPoolsByPoolIdConfigLatestErrors[keyof GetApiInternalPoolsByPoolIdConfigLatestErrors];

export type GetApiInternalPoolsByPoolIdConfigLatestResponses = {
    /**
     * Latest pool config snapshot
     */
    200: {
        poolId: string;
        version: number;
        configHash: string;
        config: {
            gateway: {
                port?: number;
                mode?: 'local';
                bind?: 'loopback' | 'lan' | 'auto';
                auth: {
                    mode: 'none' | 'token';
                    token?: string;
                };
                reload?: {
                    mode: 'off' | 'hot' | 'hybrid';
                };
                controlUi?: {
                    allowedOrigins?: Array<string>;
                    dangerouslyAllowHostHeaderOriginFallback?: boolean;
                };
            };
            models?: {
                mode?: 'merge' | 'replace';
                providers: {
                    [key: string]: {
                        baseUrl: string;
                        apiKey: string;
                        api: string;
                        models: Array<{
                            id: string;
                            name?: string;
                            reasoning?: boolean;
                            input?: Array<string>;
                            cost?: {
                                input: number;
                                output: number;
                                cacheRead?: number;
                                cacheWrite?: number;
                            };
                            contextWindow?: number;
                            maxTokens?: number;
                            compat?: {
                                supportsStore?: boolean;
                            };
                        }>;
                    };
                };
            };
            tools?: {
                exec?: {
                    security?: 'deny' | 'allowlist' | 'full';
                    ask?: 'off' | 'on-miss' | 'always';
                    host?: 'sandbox' | 'gateway' | 'node';
                };
                web?: {
                    search?: {
                        enabled?: boolean;
                    };
                    fetch?: {
                        enabled?: boolean;
                    };
                };
            };
            skills?: {
                load?: {
                    watch?: boolean;
                    watchDebounceMs?: number;
                    extraDirs?: Array<string>;
                };
            };
            agents: {
                defaults?: {
                    model?: string | {
                        primary: string;
                    };
                    compaction?: {
                        mode?: 'default' | 'safeguard';
                        reserveTokens?: number;
                        keepRecentTokens?: number;
                        reserveTokensFloor?: number;
                        maxHistoryShare?: number;
                        memoryFlush?: {
                            enabled?: boolean;
                            softThresholdTokens?: number;
                            prompt?: string;
                        };
                    };
                    memorySearch?: {
                        enabled?: boolean;
                        sources?: Array<'memory' | 'sessions'>;
                        provider?: 'openai' | 'gemini' | 'local' | 'voyage' | 'mistral';
                        model?: string;
                        remote?: {
                            baseUrl?: string;
                            apiKey?: string;
                        };
                        sync?: {
                            intervalMinutes?: number;
                        };
                    };
                };
                list: Array<{
                    id: string;
                    name?: string;
                    default?: boolean;
                    workspace?: string;
                    model?: string | {
                        primary: string;
                        fallbacks?: Array<string>;
                    };
                }>;
            };
            channels: {
                slack?: {
                    mode?: 'socket' | 'http';
                    signingSecret?: string;
                    enabled?: boolean;
                    groupPolicy?: 'open' | 'allowlist' | 'disabled';
                    requireMention?: boolean;
                    dmPolicy?: 'pairing' | 'allowlist' | 'open';
                    allowFrom?: Array<string>;
                    ackReaction?: string;
                    accounts: {
                        [key: string]: {
                            enabled?: boolean;
                            botToken: string;
                            signingSecret?: string;
                            appToken?: string;
                            mode?: 'socket' | 'http';
                            webhookPath?: string;
                            dmPolicy?: 'pairing' | 'allowlist' | 'open';
                            groupPolicy?: 'open' | 'allowlist' | 'disabled';
                            streaming?: 'off' | 'partial' | 'block' | 'progress';
                        };
                    };
                };
                discord?: {
                    enabled?: boolean;
                    groupPolicy?: 'open' | 'allowlist' | 'disabled';
                    dmPolicy?: 'pairing' | 'allowlist' | 'open';
                    allowFrom?: Array<string>;
                    accounts: {
                        [key: string]: {
                            enabled?: boolean;
                            token: string;
                            groupPolicy?: 'open' | 'allowlist' | 'disabled';
                        };
                    };
                };
                feishu?: {
                    enabled?: boolean;
                    connectionMode?: 'websocket' | 'webhook';
                    dmPolicy?: 'pairing' | 'allowlist' | 'open';
                    groupPolicy?: 'open' | 'allowlist' | 'disabled';
                    requireMention?: boolean;
                    allowFrom?: Array<string>;
                    accounts: {
                        [key: string]: {
                            enabled?: boolean;
                            appId: string;
                            appSecret: string;
                        };
                    };
                };
            };
            bindings: Array<{
                agentId: string;
                match: {
                    channel: string;
                    accountId?: string;
                };
            }>;
            commands?: {
                native?: 'auto' | 'off';
                nativeSkills?: 'auto' | 'off';
                restart?: boolean;
                ownerDisplay?: 'raw' | 'friendly';
            };
            cron?: {
                enabled?: boolean;
            };
            messages?: {
                ackReaction?: string;
                ackReactionScope?: 'off' | 'none' | 'all' | 'direct' | 'group-all' | 'group-mentions';
                removeAckAfterReply?: boolean;
            };
            diagnostics?: {
                enabled?: boolean;
                otel?: {
                    enabled?: boolean;
                    endpoint?: string;
                    serviceName?: string;
                    traces?: boolean;
                    metrics?: boolean;
                    logs?: boolean;
                    flushIntervalMs?: number;
                };
            };
        };
        agentMeta?: {
            [key: string]: {
                botId: string;
            };
        };
        poolSecrets?: {
            [key: string]: string;
        };
        secretsHash?: string;
        createdAt: string;
    };
};

export type GetApiInternalPoolsByPoolIdConfigLatestResponse = GetApiInternalPoolsByPoolIdConfigLatestResponses[keyof GetApiInternalPoolsByPoolIdConfigLatestResponses];

export type GetApiInternalPoolsByPoolIdConfigVersionsByVersionData = {
    body?: never;
    path: {
        poolId: string;
        version?: number;
    };
    query?: never;
    url: '/api/internal/pools/{poolId}/config/versions/{version}';
};

export type GetApiInternalPoolsByPoolIdConfigVersionsByVersionErrors = {
    /**
     * Config version not found
     */
    404: {
        message: string;
    };
};

export type GetApiInternalPoolsByPoolIdConfigVersionsByVersionError = GetApiInternalPoolsByPoolIdConfigVersionsByVersionErrors[keyof GetApiInternalPoolsByPoolIdConfigVersionsByVersionErrors];

export type GetApiInternalPoolsByPoolIdConfigVersionsByVersionResponses = {
    /**
     * Pool config snapshot by version
     */
    200: {
        poolId: string;
        version: number;
        configHash: string;
        config: {
            gateway: {
                port?: number;
                mode?: 'local';
                bind?: 'loopback' | 'lan' | 'auto';
                auth: {
                    mode: 'none' | 'token';
                    token?: string;
                };
                reload?: {
                    mode: 'off' | 'hot' | 'hybrid';
                };
                controlUi?: {
                    allowedOrigins?: Array<string>;
                    dangerouslyAllowHostHeaderOriginFallback?: boolean;
                };
            };
            models?: {
                mode?: 'merge' | 'replace';
                providers: {
                    [key: string]: {
                        baseUrl: string;
                        apiKey: string;
                        api: string;
                        models: Array<{
                            id: string;
                            name?: string;
                            reasoning?: boolean;
                            input?: Array<string>;
                            cost?: {
                                input: number;
                                output: number;
                                cacheRead?: number;
                                cacheWrite?: number;
                            };
                            contextWindow?: number;
                            maxTokens?: number;
                            compat?: {
                                supportsStore?: boolean;
                            };
                        }>;
                    };
                };
            };
            tools?: {
                exec?: {
                    security?: 'deny' | 'allowlist' | 'full';
                    ask?: 'off' | 'on-miss' | 'always';
                    host?: 'sandbox' | 'gateway' | 'node';
                };
                web?: {
                    search?: {
                        enabled?: boolean;
                    };
                    fetch?: {
                        enabled?: boolean;
                    };
                };
            };
            skills?: {
                load?: {
                    watch?: boolean;
                    watchDebounceMs?: number;
                    extraDirs?: Array<string>;
                };
            };
            agents: {
                defaults?: {
                    model?: string | {
                        primary: string;
                    };
                    compaction?: {
                        mode?: 'default' | 'safeguard';
                        reserveTokens?: number;
                        keepRecentTokens?: number;
                        reserveTokensFloor?: number;
                        maxHistoryShare?: number;
                        memoryFlush?: {
                            enabled?: boolean;
                            softThresholdTokens?: number;
                            prompt?: string;
                        };
                    };
                    memorySearch?: {
                        enabled?: boolean;
                        sources?: Array<'memory' | 'sessions'>;
                        provider?: 'openai' | 'gemini' | 'local' | 'voyage' | 'mistral';
                        model?: string;
                        remote?: {
                            baseUrl?: string;
                            apiKey?: string;
                        };
                        sync?: {
                            intervalMinutes?: number;
                        };
                    };
                };
                list: Array<{
                    id: string;
                    name?: string;
                    default?: boolean;
                    workspace?: string;
                    model?: string | {
                        primary: string;
                        fallbacks?: Array<string>;
                    };
                }>;
            };
            channels: {
                slack?: {
                    mode?: 'socket' | 'http';
                    signingSecret?: string;
                    enabled?: boolean;
                    groupPolicy?: 'open' | 'allowlist' | 'disabled';
                    requireMention?: boolean;
                    dmPolicy?: 'pairing' | 'allowlist' | 'open';
                    allowFrom?: Array<string>;
                    ackReaction?: string;
                    accounts: {
                        [key: string]: {
                            enabled?: boolean;
                            botToken: string;
                            signingSecret?: string;
                            appToken?: string;
                            mode?: 'socket' | 'http';
                            webhookPath?: string;
                            dmPolicy?: 'pairing' | 'allowlist' | 'open';
                            groupPolicy?: 'open' | 'allowlist' | 'disabled';
                            streaming?: 'off' | 'partial' | 'block' | 'progress';
                        };
                    };
                };
                discord?: {
                    enabled?: boolean;
                    groupPolicy?: 'open' | 'allowlist' | 'disabled';
                    dmPolicy?: 'pairing' | 'allowlist' | 'open';
                    allowFrom?: Array<string>;
                    accounts: {
                        [key: string]: {
                            enabled?: boolean;
                            token: string;
                            groupPolicy?: 'open' | 'allowlist' | 'disabled';
                        };
                    };
                };
                feishu?: {
                    enabled?: boolean;
                    connectionMode?: 'websocket' | 'webhook';
                    dmPolicy?: 'pairing' | 'allowlist' | 'open';
                    groupPolicy?: 'open' | 'allowlist' | 'disabled';
                    requireMention?: boolean;
                    allowFrom?: Array<string>;
                    accounts: {
                        [key: string]: {
                            enabled?: boolean;
                            appId: string;
                            appSecret: string;
                        };
                    };
                };
            };
            bindings: Array<{
                agentId: string;
                match: {
                    channel: string;
                    accountId?: string;
                };
            }>;
            commands?: {
                native?: 'auto' | 'off';
                nativeSkills?: 'auto' | 'off';
                restart?: boolean;
                ownerDisplay?: 'raw' | 'friendly';
            };
            cron?: {
                enabled?: boolean;
            };
            messages?: {
                ackReaction?: string;
                ackReactionScope?: 'off' | 'none' | 'all' | 'direct' | 'group-all' | 'group-mentions';
                removeAckAfterReply?: boolean;
            };
            diagnostics?: {
                enabled?: boolean;
                otel?: {
                    enabled?: boolean;
                    endpoint?: string;
                    serviceName?: string;
                    traces?: boolean;
                    metrics?: boolean;
                    logs?: boolean;
                    flushIntervalMs?: number;
                };
            };
        };
        agentMeta?: {
            [key: string]: {
                botId: string;
            };
        };
        poolSecrets?: {
            [key: string]: string;
        };
        secretsHash?: string;
        createdAt: string;
    };
};

export type GetApiInternalPoolsByPoolIdConfigVersionsByVersionResponse = GetApiInternalPoolsByPoolIdConfigVersionsByVersionResponses[keyof GetApiInternalPoolsByPoolIdConfigVersionsByVersionResponses];

export type GetApiInternalSecretsStaticDeployData = {
    body?: never;
    path?: never;
    query: {
        poolId: string;
    };
    url: '/api/internal/secrets/static-deploy';
};

export type GetApiInternalSecretsStaticDeployErrors = {
    /**
     * Pool not found
     */
    404: {
        message: string;
    };
};

export type GetApiInternalSecretsStaticDeployError = GetApiInternalSecretsStaticDeployErrors[keyof GetApiInternalSecretsStaticDeployErrors];

export type GetApiInternalSecretsStaticDeployResponses = {
    /**
     * Static deploy secrets for a pool
     */
    200: {
        CLOUDFLARE_API_TOKEN: string;
        CLOUDFLARE_ACCOUNT_ID: string;
    };
};

export type GetApiInternalSecretsStaticDeployResponse = GetApiInternalSecretsStaticDeployResponses[keyof GetApiInternalSecretsStaticDeployResponses];

export type PostApiInternalPoolsByPoolIdCheckSlackTokensData = {
    body?: never;
    path: {
        poolId: string;
    };
    query?: never;
    url: '/api/internal/pools/{poolId}/check-slack-tokens';
};

export type PostApiInternalPoolsByPoolIdCheckSlackTokensErrors = {
    /**
     * Pool not found
     */
    404: {
        message: string;
    };
};

export type PostApiInternalPoolsByPoolIdCheckSlackTokensError = PostApiInternalPoolsByPoolIdCheckSlackTokensErrors[keyof PostApiInternalPoolsByPoolIdCheckSlackTokensErrors];

export type PostApiInternalPoolsByPoolIdCheckSlackTokensResponses = {
    /**
     * Slack token health check results
     */
    200: {
        checked: number;
        invalidated: number;
        results: Array<{
            botChannelId: string;
            accountId: string;
            ok: boolean;
            error?: string;
        }>;
    };
};

export type PostApiInternalPoolsByPoolIdCheckSlackTokensResponse = PostApiInternalPoolsByPoolIdCheckSlackTokensResponses[keyof PostApiInternalPoolsByPoolIdCheckSlackTokensResponses];

export type GetApiV1ArtifactsData = {
    body?: never;
    path?: never;
    query?: {
        botId?: string;
        sessionKey?: string;
        source?: string;
        status?: string;
        limit?: number;
        offset?: number;
    };
    url: '/api/v1/artifacts';
};

export type GetApiV1ArtifactsResponses = {
    /**
     * Artifact list
     */
    200: {
        artifacts: Array<{
            id: string;
            botId: string;
            sessionKey: string;
            channelType: string;
            channelId: string;
            title: string;
            artifactType: string;
            source: string;
            contentType: string;
            status: string;
            previewUrl: string;
            deployTarget: string;
            linesOfCode: number;
            fileCount: number;
            durationMs: number;
            metadata: {
                [key: string]: unknown;
            };
            createdAt: string;
            updatedAt: string;
        }>;
        total: number;
        limit: number;
        offset: number;
    };
};

export type GetApiV1ArtifactsResponse = GetApiV1ArtifactsResponses[keyof GetApiV1ArtifactsResponses];

export type GetApiV1ArtifactsStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/artifacts/stats';
};

export type GetApiV1ArtifactsStatsResponses = {
    /**
     * Artifact statistics
     */
    200: {
        totalArtifacts: number;
        liveCount: number;
        buildingCount: number;
        failedCount: number;
        codingCount: number;
        contentCount: number;
        totalLinesOfCode: number;
    };
};

export type GetApiV1ArtifactsStatsResponse = GetApiV1ArtifactsStatsResponses[keyof GetApiV1ArtifactsStatsResponses];

export type DeleteApiV1ArtifactsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/artifacts/{id}';
};

export type DeleteApiV1ArtifactsByIdErrors = {
    /**
     * Artifact not found
     */
    404: {
        message: string;
    };
};

export type DeleteApiV1ArtifactsByIdError = DeleteApiV1ArtifactsByIdErrors[keyof DeleteApiV1ArtifactsByIdErrors];

export type DeleteApiV1ArtifactsByIdResponses = {
    /**
     * Artifact deleted
     */
    200: {
        message: string;
    };
};

export type DeleteApiV1ArtifactsByIdResponse = DeleteApiV1ArtifactsByIdResponses[keyof DeleteApiV1ArtifactsByIdResponses];

export type GetApiV1ArtifactsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/artifacts/{id}';
};

export type GetApiV1ArtifactsByIdErrors = {
    /**
     * Artifact not found
     */
    404: {
        message: string;
    };
};

export type GetApiV1ArtifactsByIdError = GetApiV1ArtifactsByIdErrors[keyof GetApiV1ArtifactsByIdErrors];

export type GetApiV1ArtifactsByIdResponses = {
    /**
     * Artifact details
     */
    200: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        artifactType: string;
        source: string;
        contentType: string;
        status: string;
        previewUrl: string;
        deployTarget: string;
        linesOfCode: number;
        fileCount: number;
        durationMs: number;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type GetApiV1ArtifactsByIdResponse = GetApiV1ArtifactsByIdResponses[keyof GetApiV1ArtifactsByIdResponses];

export type GetApiV1SessionsData = {
    body?: never;
    path?: never;
    query?: {
        botId?: string;
        channelType?: string;
        status?: string;
        limit?: number;
        offset?: number;
    };
    url: '/api/v1/sessions';
};

export type GetApiV1SessionsResponses = {
    /**
     * Session list
     */
    200: {
        sessions: Array<{
            id: string;
            botId: string;
            sessionKey: string;
            channelType: string;
            channelId: string;
            title: string;
            status: string;
            messageCount: number;
            lastMessageAt: string;
            metadata: {
                [key: string]: unknown;
            };
            createdAt: string;
            updatedAt: string;
        }>;
        total: number;
        limit: number;
        offset: number;
    };
};

export type GetApiV1SessionsResponse = GetApiV1SessionsResponses[keyof GetApiV1SessionsResponses];

export type GetApiV1SessionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/sessions/{id}';
};

export type GetApiV1SessionsByIdErrors = {
    /**
     * Session not found
     */
    404: {
        message: string;
    };
};

export type GetApiV1SessionsByIdError = GetApiV1SessionsByIdErrors[keyof GetApiV1SessionsByIdErrors];

export type GetApiV1SessionsByIdResponses = {
    /**
     * Session details
     */
    200: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        status: string;
        messageCount: number;
        lastMessageAt: string;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type GetApiV1SessionsByIdResponse = GetApiV1SessionsByIdResponses[keyof GetApiV1SessionsByIdResponses];

export type GetApiV1IntegrationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/integrations';
};

export type GetApiV1IntegrationsResponses = {
    /**
     * List of integrations with user status
     */
    200: {
        integrations: Array<{
            id?: string;
            toolkit: {
                slug: string;
                displayName: string;
                description: string;
                iconUrl: string;
                category: string;
                authScheme: 'oauth2' | 'api_key_global' | 'api_key_user';
                authFields?: Array<{
                    key: string;
                    label: string;
                    type: 'text' | 'secret';
                    placeholder?: string;
                }>;
            };
            status: 'pending' | 'initiated' | 'active' | 'failed' | 'expired' | 'disconnected';
            connectUrl?: string;
            connectedAt?: string;
            credentialHints?: {
                [key: string]: string;
            };
        }>;
    };
};

export type GetApiV1IntegrationsResponse = GetApiV1IntegrationsResponses[keyof GetApiV1IntegrationsResponses];

export type PostApiV1IntegrationsConnectData = {
    body?: {
        toolkitSlug: string;
        credentials?: {
            [key: string]: string;
        };
        source?: 'page' | 'chat';
        returnTo?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/integrations/connect';
};

export type PostApiV1IntegrationsConnectErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
    /**
     * Toolkit not found
     */
    404: {
        message: string;
    };
};

export type PostApiV1IntegrationsConnectError = PostApiV1IntegrationsConnectErrors[keyof PostApiV1IntegrationsConnectErrors];

export type PostApiV1IntegrationsConnectResponses = {
    /**
     * Connection initiated
     */
    200: {
        integration: {
            id?: string;
            toolkit: {
                slug: string;
                displayName: string;
                description: string;
                iconUrl: string;
                category: string;
                authScheme: 'oauth2' | 'api_key_global' | 'api_key_user';
                authFields?: Array<{
                    key: string;
                    label: string;
                    type: 'text' | 'secret';
                    placeholder?: string;
                }>;
            };
            status: 'pending' | 'initiated' | 'active' | 'failed' | 'expired' | 'disconnected';
            connectUrl?: string;
            connectedAt?: string;
            credentialHints?: {
                [key: string]: string;
            };
        };
        connectUrl?: string;
        state?: string;
    };
};

export type PostApiV1IntegrationsConnectResponse = PostApiV1IntegrationsConnectResponses[keyof PostApiV1IntegrationsConnectResponses];

export type PostApiV1IntegrationsByIntegrationIdRefreshData = {
    body?: {
        state: string;
    };
    path: {
        integrationId: string;
    };
    query?: never;
    url: '/api/v1/integrations/{integrationId}/refresh';
};

export type PostApiV1IntegrationsByIntegrationIdRefreshErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
    /**
     * State verification failed
     */
    403: {
        message: string;
    };
    /**
     * Integration not found
     */
    404: {
        message: string;
    };
};

export type PostApiV1IntegrationsByIntegrationIdRefreshError = PostApiV1IntegrationsByIntegrationIdRefreshErrors[keyof PostApiV1IntegrationsByIntegrationIdRefreshErrors];

export type PostApiV1IntegrationsByIntegrationIdRefreshResponses = {
    /**
     * Integration status refreshed
     */
    200: {
        id?: string;
        toolkit: {
            slug: string;
            displayName: string;
            description: string;
            iconUrl: string;
            category: string;
            authScheme: 'oauth2' | 'api_key_global' | 'api_key_user';
            authFields?: Array<{
                key: string;
                label: string;
                type: 'text' | 'secret';
                placeholder?: string;
            }>;
        };
        status: 'pending' | 'initiated' | 'active' | 'failed' | 'expired' | 'disconnected';
        connectUrl?: string;
        connectedAt?: string;
        credentialHints?: {
            [key: string]: string;
        };
    };
};

export type PostApiV1IntegrationsByIntegrationIdRefreshResponse = PostApiV1IntegrationsByIntegrationIdRefreshResponses[keyof PostApiV1IntegrationsByIntegrationIdRefreshResponses];

export type DeleteApiV1IntegrationsByIntegrationIdData = {
    body?: never;
    path: {
        integrationId: string;
    };
    query?: never;
    url: '/api/v1/integrations/{integrationId}';
};

export type DeleteApiV1IntegrationsByIntegrationIdErrors = {
    /**
     * Cannot disconnect global toolkit
     */
    403: {
        message: string;
    };
    /**
     * Integration not found
     */
    404: {
        message: string;
    };
};

export type DeleteApiV1IntegrationsByIntegrationIdError = DeleteApiV1IntegrationsByIntegrationIdErrors[keyof DeleteApiV1IntegrationsByIntegrationIdErrors];

export type DeleteApiV1IntegrationsByIntegrationIdResponses = {
    /**
     * Integration disconnected
     */
    200: {
        id?: string;
        toolkit: {
            slug: string;
            displayName: string;
            description: string;
            iconUrl: string;
            category: string;
            authScheme: 'oauth2' | 'api_key_global' | 'api_key_user';
            authFields?: Array<{
                key: string;
                label: string;
                type: 'text' | 'secret';
                placeholder?: string;
            }>;
        };
        status: 'pending' | 'initiated' | 'active' | 'failed' | 'expired' | 'disconnected';
        connectUrl?: string;
        connectedAt?: string;
        credentialHints?: {
            [key: string]: string;
        };
    };
};

export type DeleteApiV1IntegrationsByIntegrationIdResponse = DeleteApiV1IntegrationsByIntegrationIdResponses[keyof DeleteApiV1IntegrationsByIntegrationIdResponses];

export type GetApiV1SkillsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/skills';
};

export type GetApiV1SkillsResponses = {
    /**
     * List of available skills
     */
    200: {
        skills: Array<{
            slug: string;
            name: string;
            description: string;
            longDescription?: string;
            iconName: string;
            prompt: string;
            examples?: Array<string>;
            tag: 'office-collab' | 'file-knowledge' | 'creative-design' | 'biz-analysis' | 'av-generation' | 'info-content' | 'dev-tools';
            source: 'official' | 'custom';
            tools?: Array<{
                slug: string;
                name: string;
                provider: string;
            }>;
            githubUrl?: string;
        }>;
        tags: Array<{
            id: 'office-collab' | 'file-knowledge' | 'creative-design' | 'biz-analysis' | 'av-generation' | 'info-content' | 'dev-tools';
            label: string;
            count: number;
        }>;
    };
};

export type GetApiV1SkillsResponse = GetApiV1SkillsResponses[keyof GetApiV1SkillsResponses];

export type GetApiV1SkillsBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/skills/{slug}';
};

export type GetApiV1SkillsBySlugErrors = {
    /**
     * Skill not found
     */
    404: {
        message: string;
    };
};

export type GetApiV1SkillsBySlugError = GetApiV1SkillsBySlugErrors[keyof GetApiV1SkillsBySlugErrors];

export type GetApiV1SkillsBySlugResponses = {
    /**
     * Skill detail with tool auth status
     */
    200: {
        slug: string;
        name: string;
        description: string;
        longDescription?: string;
        iconName: string;
        prompt: string;
        examples?: Array<string>;
        tag: 'office-collab' | 'file-knowledge' | 'creative-design' | 'biz-analysis' | 'av-generation' | 'info-content' | 'dev-tools';
        source: 'official' | 'custom';
        tools?: Array<{
            slug: string;
            name: string;
            provider: string;
            authScheme: string;
            status: 'connected' | 'not_connected' | 'initiated' | 'expired';
            integrationId?: string;
        }>;
        githubUrl?: string;
        relatedSkills?: Array<{
            slug: string;
            name: string;
            description: string;
            longDescription?: string;
            iconName: string;
            prompt: string;
            examples?: Array<string>;
            tag: 'office-collab' | 'file-knowledge' | 'creative-design' | 'biz-analysis' | 'av-generation' | 'info-content' | 'dev-tools';
            source: 'official' | 'custom';
            tools?: Array<{
                slug: string;
                name: string;
                provider: string;
            }>;
            githubUrl?: string;
        }>;
    };
};

export type GetApiV1SkillsBySlugResponse = GetApiV1SkillsBySlugResponses[keyof GetApiV1SkillsBySlugResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};